os: osx
osx_image: xcode9.3
language: java
compiler: clang
addons:
  homebrew:
    packages:
    - maven
    - ant
    - awscli
    update: true
jobs:
  include:
    - stage: build
      name: "Build C++/Java and Upload to S3"
      before_script:
       - cd java/amazon-kinesis-producer
       - KPL_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
       - echo "Found KPL version $KPL_VERSION in current directory $PWD ... "
       - echo "Starting Packaging of KPL.$KPL_VERSION"
       - cd ../..
      script:
       - ./bootstrap.sh
       - if [[ "$TRAVIS_BRANCH" == master && "$TRAVIS_EVENT_TYPE" != pull_request ]]; then cd java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/$TRAVIS_OS_NAME; fi
       - if [[ "$TRAVIS_BRANCH" == master && "$TRAVIS_EVENT_TYPE" != pull_request ]]; then zip kinesis-producer.zip kinesis_producer; fi
       - if [[ "$TRAVIS_BRANCH" == master && "$TRAVIS_EVENT_TYPE" != pull_request ]]; then aws s3 cp kinesis-producer.zip s3://kpl-build-kinesis-internal/$KPL_VERSION/$TRAVIS_OS_NAME/kinesis-producer.zip; fi
      after_success:
        - sleep 10
      after_failure:
        - sleep 10
